
name: Create Pull Request to develop

on:
  push:
    branches:
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request to develop
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref }}
          title: 'Automatic PR from ${{ github.ref }}'
          body: |
            This pull request is automatically created from branch ${{ github.ref }}.
          labels: |
            automatic-pr
          draft: false